export const scenarios = {
  walkin: {
    name: "Walk-In Client",
    steps: [
      "Appointment scheduled",
      "Forms completed",
      "Payment confirmed",
      "Sample collected",
      "Internal QC completed",
      "Sample dispatched to laboratory",
      "Sample received by laboratory",
      "Laboratory analysis in progress",
      "Test Report Ready",
      "Result sent to provided email",
    ],
  },

  walkin_kit_pickup: {
    name: "Walk-In Client – Kit Pickup",
    steps: [
      "Payment confirmed",
      "Kit picked up by client",
      "Sample collection instructions provided",
      "Client returned completed kit",
      "Sample received and verified",
      "Internal QC completed",
      "Sample dispatched to laboratory",
      "Sample received by laboratory",
      "Laboratory analysis in progress",
      "Test Report Ready",
      "Result sent to provided email",
    ],
  },

  home_service: {
    name: "Home Service Client",
    steps: [
      "Payment confirmed",
      "Home service appointment scheduled",
      "Sample collected at client location",
      "Internal QC completed",
      "Sample dispatched to laboratory",
      "Sample received by laboratory",
      "Laboratory analysis in progress",
      "Test Report Ready",
      "Result sent to provided email",
    ],
  },

  kit_delivery: {
    name: "Kit Delivery Client",
    steps: [
      "Payment confirmed",
      "Logistics notified to dispatch kit",
      "Sample collection instructions sent",
      "Kit delivered to client",
      "Client returned completed kit",
      "Sample received and verified",
      "Internal QC completed",
      "Sample dispatched to laboratory",
      "Sample received by laboratory",
      "Laboratory analysis in progress",
      "Test Report Ready",
      "Result sent to provided email",
    ],
  },

  partner_collection: {
    name: "Sample Collection Center (Partner)",
    steps: [
      "Payment confirmed",
      "Appointment scheduled at partner center",
      "Appointment details shared with partner center",
      "Sample collected at partner center",
      "Logistics notified for pickup",
      "Sample delivered to Gbagada office",
      "Internal QC completed",
      "Sample dispatched to laboratory",
      "Sample received by laboratory",
      "Laboratory analysis in progress",
      "Test Report Ready",
      "Result sent to provided email",
    ],
  },
};
